#!/usr/bin/env sh

export LANG="${NOVNC_ANSIBLE_LOCALE:-en_US.utf8}"
export LC_ALL="${NOVNC_ANSIBLE_LOCALE:-en_US.utf8}"
export ANSIBLE_LOCAL_TEMP="${ANSIBLE_LOCAL_TEMP:-/tmp/ansible-local}"
export ANSIBLE_REMOTE_TEMP="${ANSIBLE_REMOTE_TEMP:-/tmp/ansible-remote}"
export GITHUB_TOKEN="${GITHUB_TOKEN:-}"
export PYTHONNOUSERSITE="${PYTHONNOUSERSITE:-1}"

if [ -d /home/linuxbrew/.linuxbrew/bin ]; then
  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
fi

pnpm run lint
ansible-lint
